#!/bin/bash

echo "🔍 检查GitHub用户名..."
echo ""
echo "请按以下步骤确认你的真实GitHub用户名："
echo ""
echo "方法1: 访问你的GitHub个人页面"
echo "   - 登录GitHub后，点击右上角头像"
echo "   - 查看URL: https://github.com/你的用户名"
echo "   - 用户名就是URL中的部分"
echo ""
echo "方法2: 检查设置页面"
echo "   - 访问: https://github.com/settings/profile"
echo "   - 查看'Username'字段（不是'Name'字段）"
echo ""
echo "方法3: 使用Git命令"
echo "   - 如果你之前克隆过自己的仓库："
echo "   git remote -v"
echo ""
echo "常见的用户名格式："
echo "   - xiaolei-wang (如果可用)"
echo "   - wxl1999 (搜索结果中的一个)"
echo "   - xiaoleigood (搜索结果中的一个)"
echo "   - 或其他格式"
echo ""
echo "找到用户名后，运行："
echo "   ./deploy-fix.sh 你的真实用户名"
echo ""
